# Generated by Django 5.0.4 on 2024-04-10 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concesionario_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=255)),
                ('correo', models.CharField(max_length=255)),
                ('direccion', models.CharField(max_length=255)),
                ('ciudad', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Propietario',
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='idempresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='vehiculo_list', to='concesionario_app.empresa'),
            preserve_default=False,
        ),
    ]
