# Generated by Django 5.0.4 on 2024-04-10 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concesionario_app', '0002_empresa_delete_propietario_vehiculo_idempresa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiculo',
            name='marca',
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='color',
            field=models.CharField(choices=[('Blanco', 'Blanco'), ('Negro', 'Negro'), ('Rojo', 'Rojo'), ('Verde', 'Verde'), ('Azul', 'Azul'), ('Amarillo', 'Amarillo'), ('Gris', 'Gris'), ('Naranja', 'Naranja')], max_length=255),
        ),
    ]
